# -*- coding: utf-8 -*-
"""Sanskriti_CoLab_VGG19_Training_Aug.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NWdCKc5J4EYudczRRcdqkeagkmDS0Yl5

## **Import packages and images**
"""

from tensorflow.keras import models, layers, optimizers
from tensorflow.keras.layers import Dense, Flatten, Dropout, RandomZoom, RandomContrast, RandomRotation
from tensorflow.keras.applications.vgg19 import VGG19
from tensorflow.keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, save_img
from tensorflow.keras.models import Sequential
from numpy import expand_dims, asarray
from google.colab import drive
from random import *
import os
import cv2
import matplotlib.pyplot as plt
import numpy as np
!pip install split-folders
!pip install Pillow
from PIL import Image
import splitfolders

drive.mount('/content/gdrive')

IMAGE_SIZE = (224,224)
BATCH_SIZE = 32
NUM_EPOCHS = 5 #changed 20 to 5 for testing

splitfolders.ratio('/content/gdrive/MyDrive/ACM_SkinCancer_Research/Train', output="output", seed=1337, ratio=(0.8,0.1,0.1))

train_path = 'output/train'
test_path = 'output/test'
val_path = 'output/val'

from google.colab import drive

"""Augment training & testing images"""

train_mal_size_augmentation = RandomZoom(height_factor=(0, 0.1), width_factor=(0, 0.1))
train_ben_size_augmentation = RandomZoom(height_factor=(-0.1, 0), width_factor=(-0.1, 0))

size_augmentation = RandomZoom(0.8)
contrast_augmentation = RandomContrast(0.6)
rotation_augmentation = RandomRotation(0.3)


def augment_image(np_image):

    num = randint(1, 50)

    if num == 5:
        print('before augmentation:')
        plt.axis('off')
        plt.imshow(np_image)
        plt.show()

    # Random size
    augmented_eager_tensor = size_augmentation(np_image)
    augmented_np_arr = augmented_eager_tensor.numpy()

    # Random contrast
    augmented_eager_tensor = contrast_augmentation(augmented_np_arr)
    augmented_np_arr = augmented_eager_tensor.numpy()

    # Random rotation
    augmented_eager_tensor = rotation_augmentation(augmented_np_arr)
    augmented_np_arr = augmented_eager_tensor.numpy()

    if num == 5:
        print('after augmentation:')
        plt.axis('off')
        plt.imshow(augmented_np_arr / 255)
        plt.show()

    return augmented_np_arr


for folder in os.listdir(train_path):
    sub_path = train_path + '/' + folder
    for img in os.listdir(sub_path):
        num = randint(1, 100)

        pil_img = Image.open(sub_path+'/'+img)
        os.remove(sub_path+'/'+img)
        np_image = asarray(pil_img)

        if num == 5:
            print('before training augmentation:')
            plt.axis('off')
            plt.imshow(np_image)
            plt.show()

        # Random size
        if (folder == 'malignant'):
            augmented_eager_tensor = train_mal_size_augmentation(np_image)
        else:
            augmented_eager_tensor = train_ben_size_augmentation(np_image)
        augmented_arr = augmented_eager_tensor.numpy()

        # Random contrast
        augmented_eager_tensor = contrast_augmentation(augmented_arr)
        augmented_arr = augmented_eager_tensor.numpy()

        # Random rotation
        augmented_eager_tensor = rotation_augmentation(augmented_arr)
        augmented_arr = augmented_eager_tensor.numpy()

        if num == 5:
            print('after training augmentation:')
            plt.axis('off')
            plt.imshow(augmented_arr / 255)
            plt.show()

        augmented_image = Image.fromarray(augmented_arr.astype(np.uint8))

        fullpath = os.path.join(sub_path, 'new_' + img)
        augmented_image.save(fullpath)


for folder in os.listdir(test_path):
    sub_path = test_path+'/'+folder
    for img in os.listdir(sub_path):
        pil_img = Image.open(sub_path+'/'+img)
        os.remove(sub_path+'/'+img)
        np_image = asarray(pil_img)

        augmented_arr = augment_image(np_image)

        augmented_image = Image.fromarray(augmented_arr.astype(np.uint8))

        fullpath = os.path.join(sub_path, 'new_' + img)
        augmented_image.save(fullpath)


for folder in os.listdir(val_path):
    sub_path = val_path+'/'+folder
    for img in os.listdir(sub_path):
        pil_img = Image.open(sub_path+'/'+img)
        os.remove(sub_path+'/'+img)
        np_image = asarray(pil_img)

        augmented_arr = augment_image(np_image)

        augmented_image = Image.fromarray(augmented_arr.astype(np.uint8))

        fullpath = os.path.join(sub_path, 'new_' + img)
        augmented_image.save(fullpath)

DATAGEN = ImageDataGenerator(rescale = 1./255, validation_split=0.2)


training_set = DATAGEN.flow_from_directory(train_path,
                                                 target_size = IMAGE_SIZE,
                                                 batch_size = BATCH_SIZE,
                                                 class_mode = 'categorical')

test_set = DATAGEN.flow_from_directory(test_path,
                                            target_size = IMAGE_SIZE,
                                            batch_size = BATCH_SIZE,
                                            class_mode = 'categorical')

val_set = DATAGEN.flow_from_directory(val_path,
                                            target_size = IMAGE_SIZE,
                                            batch_size = BATCH_SIZE,
                                            class_mode = 'categorical')

"""## **Initialize VGG19 DCNN model, trained on ImageNet**"""

vgg_19 = VGG19(weights='imagenet', include_top=False, input_shape = (224,224,3))

set_trainable = False
for layer in vgg_19.layers:
    layer.trainable = False

model = models.Sequential()

model.add(vgg_19)

model.add(layers.Flatten())

model.add(layers.Dense(256, activation='relu'))
model.add(layers.Dropout(0.3))

model.add(layers.Dense(128, activation='relu'))
model.add(layers.Dropout(0.2))

model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dropout(0.2))

model.add(layers.Dense(11, activation='softmax')) #changed 2 to 11 (11 diff categories)

model.compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizers.Adam(learning_rate=2e-5),
  metrics = ['accuracy']
)

history = model.fit(
  training_set,
  steps_per_epoch = training_set.samples // BATCH_SIZE,
  epochs = NUM_EPOCHS,
  validation_data = val_set,
  validation_steps = val_set.samples // BATCH_SIZE,
  shuffle = True
  )

"""## **Plot accuracy before Transfer Learning**"""

def plot_accuracy_loss(history):
    plt.plot(history.history['accuracy'])
    plt.plot(history.history['val_accuracy'])
    plt.title('model accuracy')
    plt.ylabel('accuracy')
    plt.xlabel('epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.show()

# summarize history for loss
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.ylabel('loss')
    plt.xlabel('epoch')
    plt.legend(['Train', 'Validation'], loc='upper left')
    plt.show()

plot_accuracy_loss(history)

test_loss, test_acc = model.evaluate(test_set, steps=test_set.samples // BATCH_SIZE)
print(f"Test Accuracy before fine tuning: {test_acc*100:.2f} %")

"""## **Fine-tune hyperparameters to optimize performance**"""

vgg_19.trainable = True

set_trainable = False
for layer in vgg_19.layers:
    if layer.name=='block5_conv1':
        set_trainable = True
    if set_trainable == True:
        layer.trainable = True
    else:
        layer.trainable = False

model.compile(
  loss = 'categorical_crossentropy',
  optimizer = optimizers.Adam(learning_rate=2e-5),
  metrics = ['accuracy']
)

history = model.fit(
  training_set,
  steps_per_epoch = training_set.samples // BATCH_SIZE,
  epochs = NUM_EPOCHS,
  validation_data = val_set,
  validation_steps = val_set.samples // BATCH_SIZE,
  shuffle = True
  )

"""## **Plot accuracy after Transfer Learning**"""

plot_acc_loss(history)

test_loss, test_acc = model.evaluate(test_set, steps=test_set.samples // BATCH_SIZE)
print(f"Test Accuracy After fine tuning: {test_acc*100:.2f} %")